num_labelled: 500      # ~4% of training set
acq_size: 250          # acquire 250 per iteration
num_iter: 20           # 500 + 250*20 = 5,500 (well below 11,764)
min_train: 500         # should match num_labelled or be less
balanced: True
random_split: True
m: Null