num_labelled: 20      # ~4% of training set
acq_size: 20          # acquire 250 per iteration
num_iter: 20          
min_train: 20         # should match num_labelled or be less
balanced: True
random_split: True
m: Null
diversity_rerank: true        # enable BALD + diversity
diversity_oversample: 5       # take top (factor * acq_size) before diversity filter